name: ItemsCooldown
version: '1.0-FINAL'
main: ar.com.octaviofarias.itemscooldown.ItemsCooldown
author: "OctavioFarias"
api-version: '1.21'
commands:
  cooldown:
    permission: "itemscooldown.command"
    usage: "/cooldown <player> <material> <seconds>"
    description: "Add a item/block cooldown to a player"