name: ItemsCooldown
version: '1.0-FINAL'
main: ar.com.octaviofarias.itemscooldown.ItemsCooldown
author: "OctavioFarias"
api-version: '1.21'
commands:
  cooldown:
    description: "Add a item/block cooldown to a player"